### ISSUE TITLE
To be able to use databricks cluster as fastapi rest server

### ISSUE THREAD

**Issue by DixitAdh** [stikkireddy/dbtunnel#19]
Hi @stikkireddy I tried to create a fastapi app that can the call the openai endpoint and return the response. I am not sure whether this is possible with dbtunnel fastapi app. Can you please tell me if this functionality can be achieved using this?

**Comment by stikkireddy** [comment]
hey @DixitAdh dbtunnel is only meant for rendering Web UIs and not rest apis. You cannot access the endpoint outside of the browser since it relies on session cookies. You can use it to test the openapi docs but even that may not work properly out of the box since the url is very different. I would recommend you to wait for lakehouse apps or use another serving solution for rest apis. If you are rendering an application in UI dbtunnel will fit well because it will be accessed via browser. 

hope this helps.
